name: ESLint

on:
  push:
    paths:
      - '**.ts'
  pull_request:
    paths:
      - '**.ts'
  workflow_dispatch:

jobs:
  eslint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd ./resources/angular && npm i
      - run: cd ./resources/angular && npx eslint src --ext .ts
