name: Larastan

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  larastan:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
      - uses: actions/checkout@v2
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v1"
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse
